#!/bin/python3.6

import sys
import os
import argparse
import re
import random
from submit_bsub import main as submit_jobs
from defs import *
from defs import check_keyword_in_file as check_error
from info import *

sys.path.append(get_workpath()+'/cfg')
try :
    import m_cfg
except :
    print(blue_info('[m_cfg]') + ' No m_cfg found, use default configuration')

parser = argparse.ArgumentParser(prog = 'lqcsim')
parser.add_argument('case_name'                                      , type = str, help = 'simulation case name, re wildcard accepted', nargs = '*')
parser.add_argument('-C' , '-c', '--com_opts' , action = 'append'    , type = str, help = 'append vcs compile options'                , nargs = '*')
parser.add_argument('-E' , '-e', '--ela_opts' , action = 'append'    , type = str, help = 'append vcs elaboration options'            , nargs = '*')
parser.add_argument('-S' , '-s', '--sim_opts' , action = 'append'    , type = str, help = 'append vcs simulation options'             , nargs = '*')
parser.add_argument('-d' , '--dry_run'        , action = 'store_true'            , help = 'print command only, not execute')
parser.add_argument('-co', '--compile_only'   , action = 'store_true'            , help = 'compile and elaboration only')
parser.add_argument('-ro', '-r', '--run_only' , action = 'store_true'            , help = 'simulation only')
parser.add_argument('-o' , '--out_dir'        , default = 'sims'     , type = str, help = 'output directory, default sims')
parser.add_argument('-b' , '-l', '--bsub_opts', default = 'default'  , type = str, help = 'designate bsub options, uncompleted'       , nargs = '?')
parser.add_argument('-w' , '--wave_on'        , action = 'store_true'            , help = 'dump wave on, off if skipped')
parser.add_argument('-seed'                   , default = 'random'   , type = str, help = 'simulation seed, random if skipped')
parser.add_argument('--show_case'             , action = 'store_true'            , help = 'display all valid cases in m_cfg')
parser.add_argument('-comrtl', '--compile_rtl', action = 'store_true'            , help = 'compile rtl only')
parser.add_argument('-comenv', '--compile_env', action = 'store_true'            , help = 'compile testbench only(testbench.sv not included)')
parser.add_argument('-ps', '--print_summary'  , action = 'store_true'            , help = 'print last regression summary')

args = parser.parse_args()

out_dir = 'default'
paths = {}

def parse_depends(caseName) :
    depends = set()
    if caseName == [] :
        return ['base']
    for i in caseName :
        depends.add(m_cfg.depends[i])
    return list(depends)

def parse_case_name() :
    caseName = []
    workpath = os.environ.get('WORKPATH')
    print('Working path is WORKPATH:{:s}'.format(os.environ.get('WORKPATH')))
    if len(args.case_name) == 0 and args.compile_only == False and args.compile_rtl == False and args.compile_env == False :
        sys.exit()
    else :
        for parse in args.case_name :
            m_str = parse.split()
            for case_parse in m_str :
                case_parse_re = case_parse.replace('*','.*')
                if any(re.search(case_parse_re,i) for i in m_cfg.caseName) :
                    for i in m_cfg.caseName :
                        if re.search(case_parse_re,i) != None :
                            caseName.append(i)
                else :
                    warn_info(f'{case_parse} is not a valid case')
    return caseName

def parse_paths(com_depend_list,caseName) :
    global paths
    paths['sim'] = '{:s}/{:s}'.format(get_workpath(),args.out_dir)
    paths['tb']  = '{:s}/tb'.format(paths['sim'])
    paths['tc']  = '{:s}/tc'.format(paths['sim'])
    for i in com_depend_list :
        paths[i] = '{:s}/{:s}'.format(paths['tb'],i)
    for i in caseName :
        paths[i] = '{:s}/{:s}'.format(paths['tc'],i)
    for i in paths :
        if os.path.exists(paths[i]) == False :
            os.mkdir(paths[i])
    return paths

def parse_com_opts(com_depend_list) :
    workpath = os.environ['WORKPATH']
    com_cmd_list = []
    for build in com_depend_list :
        base_com_cmd = []
        base_com_cmd.append(' -sverilog'              )
        base_com_cmd.append(' +v2k'                   )
        base_com_cmd.append(' -full64'                )
        base_com_cmd.append(' +plusarg_save'          )
        base_com_cmd.append(' +vcs+lic+wait'          )
        base_com_cmd.append(' -debug_access+all'      )
        base_com_cmd.append(' +error+99'              )
        base_com_cmd.append(' +nospecify'             )
        base_com_cmd.append(' +notimingcheck'         )
        base_com_cmd.append(' -timescale=1ns/1ps'     )
        base_com_cmd.append(' -ntb_opts uvm-1.1'      )
        if args.compile_rtl != True :
            base_com_cmd.append(' -top harness'           )
        base_com_cmd.append(' -debug_access+all'      )
        base_com_cmd.append(' -kdb'                   )
        base_com_cmd.append(' -lca'                   )
        env_flist = '{:s}/cfg/env.f'.format(workpath)
        rtl_flist = '{:s}/cfg/dut.f'.format(workpath)
        cmp_log   = '{:s}/cmp.log'.format(paths[build])
        simv      = '{:s}/simv'.format(paths[build])
        Mdir      = '{:s}/csrc'.format(paths[build])
        if args.compile_rtl != True :
            base_com_cmd.append(' -f {:s}'.format(env_flist))
        if args.compile_env != True :
            base_com_cmd.append(' -f {:s}'.format(rtl_flist))
        base_com_cmd.append(' -l {:s}'.format(cmp_log))
        base_com_cmd.append(' -o {:s}'.format(simv))
        base_com_cmd.append(' -Mdir={:s}'.format(Mdir))
        base_com_cmd.append(m_cfg.com_opts[build])
        com_cmd = ''
        for i in base_com_cmd :
            com_cmd += i
        if args.com_opts != None :
            for i in args.com_opts :
                for j in i :
                    try :
                        m_com_opts += ' ' + j
                    except :
                        m_com_opts = ' ' + j
            com_cmd += m_com_opts
        com_cmd_list.append(com_cmd)
    return com_cmd_list

def parse_sim_opts(caseName) :
    workpath = os.environ['WORKPATH']
    sim_cmd_list = []
    #uvm_verbosity = '+UVM_VERBOSITY=UVM_LOW'
    #if args.sim_opts != None :
    #    for i in args.sim_opts :
    #        for j in i :
    #            if 'UVM_VERBOSITY' in j :
    #                uvm_verbosity = j
    #                break
    for case in caseName :
        base_sim_cmd = []
        base_sim_cmd.append(' +vcs+lic+wait')
        base_sim_cmd.append(' +fsdb+force')
        base_sim_cmd.append(' -assert')
        base_sim_cmd.append(' nopostproc')
        #base_sim_cmd.append(' +UVM_MAX_QUIT_COUNT=99,0')
        base_sim_cmd.append(' +uvm_set_severity=*,RNDFLD,UVM_WARNING,UVM_FATAL')
        base_sim_cmd.append(' -ucli')
        #base_sim_cmd.append(' +UVM_TESTNAME={:s}'.format(case))
        #base_sim_cmd.append(' +tc={:s}'.format(case))
        #base_sim_cmd.append(' ' + uvm_verbosity)
        if args.seed == 'random' :
            seed = str(random.randint(0,999999))
        else :
            try :
                int(args.seed)
                seed = args.seed
            except :
                error_info('seed ({:s}) is not int !!!'.format(args.seed))
                sys.exit()
        base_sim_cmd.append(' +ntb_random_seed={:s}'.format(seed))
        base_sim_cmd.append(' +seed={:s}'.format(seed))
        run_log = '{:s}/run.log'.format(paths[case])
        base_sim_cmd.append(' -l {:s}'.format(run_log))
        base_sim_cmd.append(' -do {:s}/cfg/wave.do'.format(workpath))
        if args.wave_on == True :
            fsdb_file = '{:s}/wave.fsdb'.format(paths[case])
            base_sim_cmd.append(' +fsdbfile+{:s}'.format(fsdb_file))
            base_sim_cmd.append(' +fsdb+dump_log=off')
            base_sim_cmd.append(' +fsdb+force')
            #base_sim_cmd.append(' +fsdb+delta')
            #base_sim_cmd.append(' +fsdb+glitch=0')
        try :
            base_sim_cmd.append(m_cfg.sim_opts[case])
        except :
            error_info('sim_opts must be set(+UVM_TESTNAME at least) !!!')
            sys.exit()
        sim_cmd = ''
        m_sim_opts = ''
        for i in base_sim_cmd :
            sim_cmd += i
        if args.sim_opts != None :
            for i in args.sim_opts :
                for j in i :
                    m_sim_opts += ' ' + j
            sim_cmd += m_sim_opts
        sim_cmd = '{:s}/simv'.format(paths[m_cfg.depends[case]]) + sim_cmd
        sim_cmd_list.append(sim_cmd)
    return sim_cmd_list

def summary_print(sim_cmd_list,caseName) :
    summary = ''
    print('')
    for index,sim_cmd in enumerate(sim_cmd_list) :
        for i in re.findall(r'\/[^ ]*\/run\.log',sim_cmd) :
            run_log = ('{:s}'.format(i.strip()))
        if check_error(run_log) :
            summary += '{:s} {:s}\n'.format(red_info('[fail]',True),caseName[index])
            #print('{:s} {:s}'.format(red_info('[fail]',True),caseName[index]))
        else :
            summary += '{:s} {:s}\n'.format(green_info('[pass]',True),caseName[index])
            #print('{:s} {:s}'.format(green_info('[pass]',True),caseName[index]))
        for i in re.findall(r'\+ntb_random_seed=\d*',sim_cmd) :
            summary += '[seed] {:s}\n'.format(i.strip().split('=')[1])
            #print('[seed] {:s}'.format(i.strip().split('=')[1]))
        summary += f'[run.log path] {run_log}\n'
        #print(f'[run.log path] {run_log}')
        for i in re.findall(r'\/[^ ]*\/wave\.fsdb',sim_cmd) :
            summary += '[wave.fsdb path] {:s}\n'.format(i.strip())
            #print('[wave.fsdb path] {:s}'.format(i.strip()))
    print(summary)

def main() :
    global out_dir
    global paths
    if args.show_case :
        print(m_cfg.caseName)
        print('total count: {:0d}'.format(len(m_cfg.caseName)))
        sys.exit()
    workpath = get_workpath()
    out_dir  = args.out_dir
    caseName = parse_case_name()
    depends  = parse_depends(caseName)
    paths    = parse_paths(depends,caseName)
    com_cmd  = parse_com_opts(depends)
    os.chdir('{:s}/{:s}'.format(workpath,out_dir))
    sim_cmd_list  = parse_sim_opts(caseName)
    if args.print_summary == True :
        summary_print(sim_cmd_list,caseName)
        return
    print('Outputing into directory {:s}/{:s}'.format(workpath,out_dir))
    white_info('\n************ Start simulation ************\n',True,True)
    if args.bsub_opts != 'default' :
        try :
            bsub_cmd = 'bsub ' + args.bsub_opts
        except :
            bsub_cmd = 'bsub '
    else :
        bsub_cmd = 'bsub -I'
    if args.compile_env == True or args.compile_rtl == True :
        args.compile_only = True
    if args.run_only != True :
        light_blue_info('<<<<<<<< compile command >>>>>>>>',True,True)
        for index,cmd in enumerate(com_cmd) :
            com_cmd[index] = 'vcs' + cmd
            print('{:s} {:s} {:s}'.format(light_blue_info(f'[{depends[index]}]',True),bsub_cmd,com_cmd[index]))
        if args.dry_run != True :
            for build in depends:
                rename_hist_files(paths[build],'cmp.log')
            if len(depends) == 1 :
                os.system('{:s} {:s}'.format(bsub_cmd,com_cmd[0]))
            else :
                submit_jobs(com_cmd,depends)
            for cmd in com_cmd :
                for i in re.findall(r'\/[^ ]*\/cmp\.log',cmd) :
                    cmp_log = i.strip()
                #print(f'\033[32m[cmp.log path]\033[0m {cmp_log}\n')
                if check_error(cmp_log,[r'\b^Error\b'],0) :
                    print(red_info('\n[fail]',True)+f' {cmp_log}')
                    sys.exit()
                else :
                    print(green_info('\n[pass]',True)+f' {cmp_log}')

    if len(caseName) == 1 :
        bsub_cmd = 'bsub -I'
    else : 
        bsub_cmd = 'bsub'

    if args.compile_only != True :
        print('')
        light_blue_info('<<<<<<<< sim command >>>>>>>>',True,True)
        if args.dry_run != True :
            for case in caseName:
                rename_hist_files(paths[case],'run.log')
        if len(sim_cmd_list) == 1 :
            print('{:s} {:s} {:s}'.format(light_blue_info(f'[{caseName[0]}]',True),bsub_cmd,sim_cmd_list[0]))
            if args.dry_run != True :
                os.system('{:s} {:s}'.format(bsub_cmd,sim_cmd_list[0]))
        else :
            for index,sim_cmd in enumerate(sim_cmd_list) :
                print('{:s} {:s} {:s}'.format(light_blue_info(f'[{caseName[index]}]',True),bsub_cmd,sim_cmd))
            if args.dry_run != True :
                submit_jobs(sim_cmd_list,caseName)
        #for sim_cmd in sim_cmd_list :
        #    print('\033[1;31m[sim command] \033[0m{:s} {:s}'.format(bsub_cmd,sim_cmd))
        #    if args.dry_run != True :
        #        os.system('{:s} {:s}'.format(bsub_cmd,sim_cmd))
        if args.dry_run != True :
            summary_print(sim_cmd_list,caseName)
            #summary = ''
            #print('')
            #for index,sim_cmd in enumerate(sim_cmd_list) :
            #    for i in re.findall(r'\/[^ ]*\/run\.log',sim_cmd) :
            #        run_log = ('{:s}'.format(i.strip()))
            #    if check_error(run_log) :
            #        summary += '{:s} {:s}\n'.format(red_info('[fail]',True),caseName[index])
            #        #print('{:s} {:s}'.format(red_info('[fail]',True),caseName[index]))
            #    else :
            #        summary += '{:s} {:s}\n'.format(green_info('[pass]',True),caseName[index])
            #        #print('{:s} {:s}'.format(green_info('[pass]',True),caseName[index]))
            #    for i in re.findall(r'\+ntb_random_seed=\d*',sim_cmd) :
            #        summary += '[seed] {:s}\n'.format(i.strip().split('=')[1])
            #        #print('[seed] {:s}'.format(i.strip().split('=')[1]))
            #    summary += f'[run.log path] {run_log}\n'
            #    #print(f'[run.log path] {run_log}')
            #    for i in re.findall(r'\/[^ ]*\/wave\.fsdb',sim_cmd) :
            #        summary += '[wave.fsdb path] {:s}\n'.format(i.strip())
            #        #print('[wave.fsdb path] {:s}'.format(i.strip()))
            #print(summary)
            #if len(sim_cmd_list) > 1 :
            #    rename_hist_files(paths['tc'],'summary.log')
            #    with open(paths['tc']+'/summary.log', mode = 'w') as file :
            #        file.write(summary)

if __name__ == '__main__' :
    main()

#def font(font_color,backgroud,mode) :
#    ['DEFAULT']   = '0'
#    ['BRIGHT']    = '1'
#    ['UNDERLINE'] = '4'
#    ['BLACK']     = '30'
#    ['RED']       = '31'
#    ['GREEN']     = '32'
#    ['YELLOW']    = '33'
#    ['BLUE']      = '34'
#    ['MAGENTA']   = '35'
#    ['CYAN']      = '36'
#    ['WHITE']     = '37'
#    return
